version: '3.8'

services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: postgres_container
    environment:
      POSTGRES_USER: cuerno
      POSTGRES_PASSWORD: cuerno
      POSTGRES_DB: security_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.8-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: spring_security_example_app_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_container:5432/security_example
      SPRING_DATASOURCE_USERNAME: cuerno
      SPRING_DATASOURCE_PASSWORD: cuerno

volumes:
  postgres_data:
  redis_data:
