version: '3.8'

services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: postgres_container
    environment:
      POSTGRES_USER: cuerno
      POSTGRES_PASSWORD: cuerno
      POSTGRES_DB: security_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
